version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rental_db
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rental_user -d rental_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rental_network

volumes:
  postgres_data:

networks:
  rental_network:
    driver: bridge