//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 11:58:51 PM CET 
//


package com.example.nikitadev.hs02222025.model.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.nikitadev.hs02222025 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.nikitadev.hs02222025
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IsProperRequest }
     * 
     */
    public IsProperRequest createIsProperRequest() {
        return new IsProperRequest();
    }

    /**
     * Create an instance of {@link SoapFraction }
     * 
     */
    public SoapFraction createFraction() {
        return new SoapFraction();
    }

    /**
     * Create an instance of {@link IsProperResponse }
     * 
     */
    public IsProperResponse createIsProperResponse() {
        return new IsProperResponse();
    }

    /**
     * Create an instance of {@link ReduceRequest }
     * 
     */
    public ReduceRequest createReduceRequest() {
        return new ReduceRequest();
    }

    /**
     * Create an instance of {@link ReduceResponse }
     * 
     */
    public ReduceResponse createReduceResponse() {
        return new ReduceResponse();
    }

    /**
     * Create an instance of {@link OperationRequest }
     * 
     */
    public OperationRequest createOperationRequest() {
        return new OperationRequest();
    }

    /**
     * Create an instance of {@link OperationResponse }
     * 
     */
    public OperationResponse createOperationResponse() {
        return new OperationResponse();
    }

}
