//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 11:58:51 PM CET 
//


package com.example.nikitadev.hs02222025.model.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fraction1" type="{http://example.com/nikitadev/hs02222025}fraction"/&gt;
 *         &lt;element name="fraction2" type="{http://example.com/nikitadev/hs02222025}fraction"/&gt;
 *         &lt;element name="operationType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fraction1",
    "fraction2",
    "operationType"
})
@XmlRootElement(name = "operationRequest")
public class OperationRequest {

    @XmlElement(required = true)
    protected SoapFraction fraction1;
    @XmlElement(required = true)
    protected SoapFraction fraction2;
    @XmlElement(required = true)
    protected String operationType;

    /**
     * Gets the value of the fraction1 property.
     * 
     * @return
     *     possible object is
     *     {@link SoapFraction }
     *     
     */
    public SoapFraction getFraction1() {
        return fraction1;
    }

    /**
     * Sets the value of the fraction1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapFraction }
     *     
     */
    public void setFraction1(SoapFraction value) {
        this.fraction1 = value;
    }

    /**
     * Gets the value of the fraction2 property.
     * 
     * @return
     *     possible object is
     *     {@link SoapFraction }
     *     
     */
    public SoapFraction getFraction2() {
        return fraction2;
    }

    /**
     * Sets the value of the fraction2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoapFraction }
     *     
     */
    public void setFraction2(SoapFraction value) {
        this.fraction2 = value;
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationType(String value) {
        this.operationType = value;
    }

}
