//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.03.03 at 11:58:51 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/nikitadev/hs02222025", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.nikitadev.hs02222025.model.soap;
